/* Phase 9 tuning. Every number "The Post" moves lives here. Per §14: if pacing
   is off, adjust VIRAL_BASE / EMBARRASS_BASE and the caption deltas first —
   never the crew unlock thresholds or the per-post attract lists. */

import type { CrewDef, CrewId } from '../state/types'

export const P9 = {
  VIRAL_BASE: 0.1,
  EMBARRASS_BASE: 0.1,
  EGO_VIRAL_PER_POINT: 0.015,
  REP_STEADY_MIN: 15,
  REP_HIGH: 70,
  MAX_ATTRACT_LEADS: 3,
  SKIP_STREAK_REP_DECAY: 1,
  SKIP_STREAK_TRIGGER: 3,
} as const

/** One crew is active at a time: the highest tier unlocked. `viralUpside` adds
 *  to the viral chance; `embarrassWeightMult` multiplies the embarrass chance;
 *  `teamLeadBonus` (team only) adds +1 to leads generated by any post. */
export const CREWS: CrewDef[] = [
  {
    id: 'none',
    label: 'Just your phone',
    embarrassWeightMult: 1,
    viralUpside: 0,
    teamLeadBonus: 0,
  },
  {
    id: 'freelancer',
    label: 'A guy named Kyle with a gimbal',
    embarrassWeightMult: 0.7,
    viralUpside: 0.03,
    teamLeadBonus: 0,
  },
  {
    id: 'team',
    label: 'A full content team (three Kyles)',
    embarrassWeightMult: 0.4,
    viralUpside: 0.08,
    teamLeadBonus: 1,
  },
]

export const crewOf = (id: CrewId): CrewDef =>
  CREWS.find((c) => c.id === id) ?? CREWS[0]

/** Logged once, only on an upward change (§3). */
export const CREW_UNLOCK_LINES: Record<Exclude<CrewId, 'none'>, string> = {
  freelancer:
    'You hired Kyle. Kyle has a gimbal and a vision. The vision is mostly slow-motion walking.',
  team: "You now have a full content team. Three people named Kyle. They finish each other's transitions.",
}
